services:
  api:
    build: .
    image: ota-api:latest
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Server=db;Database=RsDb;User Id=sa;Password=YourStrong@Passw0rd123;TrustServerCertificate=True;Encrypt=False;MultipleActiveResultSets=True
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: YourStrong@Passw0rd123
      MSSQL_PID: Developer
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
